name: 배포
on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: CI=false npm run keycloak 
      - name: Create release 
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ![image](https://jjalbang.today/jjv2KQ.jpg)
            - 깃헙 액션에서 자동으로 생성됨
          draft: true
          prerelease: false
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build_keycloak/target/uyuni-suite-keycloak-theme-1.2.5.2.jar
          asset_name: uyuni-suite-keycloak-theme-${{github.ref_name}}.jar
          asset_content_type: application/java-archive
      - name: Publish release
        uses: StuYarrow/publish-release@v1.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          id: ${{ steps.create_release.outputs.id }}
    
  change_uyuni_deploy:
    if: false == contains(github.ref_name , '-') #v1.2.5.4-seoul-tech 같은 - 문자가 없도록 조건문 추가
    needs: build
    name: 릴리즈 배포후 설치코드 변경
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Uyuni_Deploy
        uses: actions/checkout@v3
        with:
          repository: 'https://github.com/xiilab/Uyuni_Deploy.git'
          token: ${{ secrets.TOKEN }}
      - run: |
          sed -i 's/\<themeUrl.*/themeUrl: https://github.com/xiilab/keycloak-theme-uyuni/releases/download/${{github.ref_name}}/uyuni-suite-keycloak-theme-${{github.ref_name}}.jar/' ./environments/default/values.yaml
          git add ./environments/default/values.yaml
          git commit -m "깃헙액션에서 자동으로 치환됨"
          git push